/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultHubPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  githubToken: "",
  defaultCategories: [],
  vaultHubUrl: "http://localhost:3000",
  publishedResources: []
};
var VaultHubSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Vault Hub Settings" });
    new import_obsidian.Setting(containerEl).setName("GitHub Personal Access Token").setDesc("Token used to create repos and push files. Requires 'repo' scope.").addText(
      (text) => text.setPlaceholder("ghp_xxxxxxxxxxxx").setValue(this.plugin.settings.githubToken).then((t) => {
        t.inputEl.type = "password";
        t.inputEl.style.width = "300px";
      }).onChange(async (value) => {
        this.plugin.settings.githubToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Vault Hub URL").setDesc("URL of the Vault Hub website (default: http://localhost:3000 for development).").addText(
      (text) => text.setPlaceholder("http://localhost:3000").setValue(this.plugin.settings.vaultHubUrl).onChange(async (value) => {
        this.plugin.settings.vaultHubUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Categories").setDesc("Comma-separated list of default categories for new publications.").addText(
      (text) => text.setPlaceholder("appearance, workflow").setValue(this.plugin.settings.defaultCategories.join(", ")).onChange(async (value) => {
        this.plugin.settings.defaultCategories = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/modals/PublishModal.ts
var import_obsidian2 = require("obsidian");

// src/detection.ts
var MD_PATTERNS = [
  [/```dataviewjs/m, "dataview"],
  [/```dataview/m, "dataview"],
  [/```datacore/m, "datacore"],
  [/```tasks/m, "obsidian-tasks-plugin"],
  [/```kanban/m, "obsidian-kanban"],
  [/```excalidraw/m, "obsidian-excalidraw-plugin"],
  [/```chart/m, "obsidian-charts"],
  [/```cards-timeline/m, "any-block"],
  [/```button/m, "buttons"],
  [/```meta-bind/m, "obsidian-meta-bind-plugin"],
  [/`=\s*this\./m, "dataview"],
  [/`=\s*dv\./m, "dataview"],
  [/`\$=\s*dv\./m, "dataview"],
  [/<%\s*tp\./m, "templater-obsidian"],
  [/<%[-_*]?\s/m, "templater-obsidian"],
  [/kanban-plugin:/m, "obsidian-kanban"],
  [/^banner:/m, "obsidian-banners"]
];
var CSS_PATTERNS = [
  [/\.dataview/i, "dataview"],
  [/\.kanban/i, "obsidian-kanban"],
  [/\.tasks-plugin/i, "obsidian-tasks-plugin"],
  [/\.excalidraw/i, "obsidian-excalidraw-plugin"],
  [/\.cm-table-widget/i, "table-editor-obsidian"]
];
async function getInstalledPlugins(vault) {
  const plugins = [];
  const pluginsDir = `${vault.configDir}/plugins`;
  const listing = await vault.adapter.list(pluginsDir);
  for (const folder of listing.folders) {
    const manifestPath = `${folder}/manifest.json`;
    try {
      const raw = await vault.adapter.read(manifestPath);
      const manifest = JSON.parse(raw);
      plugins.push({
        id: manifest.id,
        name: manifest.name,
        version: manifest.version,
        author: manifest.author,
        autoDetected: false
      });
    } catch (e) {
    }
  }
  return plugins;
}
async function detectPlugins(fileContent, fileType, vault) {
  const installed = await getInstalledPlugins(vault);
  const installedIds = new Set(installed.map((p) => p.id));
  const detectedIds = /* @__PURE__ */ new Set();
  const patterns = fileType === "css" ? CSS_PATTERNS : MD_PATTERNS;
  for (const [regex, pluginId] of patterns) {
    if (regex.test(fileContent) && installedIds.has(pluginId)) {
      detectedIds.add(pluginId);
    }
  }
  return installed.map((p) => ({
    ...p,
    autoDetected: detectedIds.has(p.id)
  }));
}

// src/github.ts
var GitHubAPI = class {
  constructor(token) {
    this.token = token;
  }
  async request(path, options = {}) {
    const res = await fetch(`https://api.github.com${path}`, {
      ...options,
      headers: {
        Authorization: `token ${this.token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        ...options.headers
      }
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`GitHub API ${res.status}: ${body}`);
    }
    return res.json();
  }
  async getUser() {
    return this.request("/user");
  }
  async createRepo(name, description) {
    return this.request("/user/repos", {
      method: "POST",
      body: JSON.stringify({
        name,
        description,
        auto_init: false,
        private: false
      })
    });
  }
  async addTopics(owner, repo, topics) {
    return this.request(`/repos/${owner}/${repo}/topics`, {
      method: "PUT",
      body: JSON.stringify({ names: topics })
    });
  }
  async createFile(owner, repo, path, content, message) {
    const encoded = btoa(unescape(encodeURIComponent(content)));
    return this.request(`/repos/${owner}/${repo}/contents/${path}`, {
      method: "PUT",
      body: JSON.stringify({ message, content: encoded })
    });
  }
  async updateFile(owner, repo, path, content, message, sha) {
    const encoded = btoa(unescape(encodeURIComponent(content)));
    return this.request(`/repos/${owner}/${repo}/contents/${path}`, {
      method: "PUT",
      body: JSON.stringify({ message, content: encoded, sha })
    });
  }
  async getFileContent(owner, repo, path) {
    try {
      const data = await this.request(
        `/repos/${owner}/${repo}/contents/${path}`
      );
      return { sha: data.sha, content: atob(data.content) };
    } catch (e) {
      return null;
    }
  }
};

// src/hubyml.ts
function generateHubYml(data) {
  const lines = [];
  lines.push("schema: 1");
  lines.push(`type: ${data.type}`);
  lines.push(`name: "${esc(data.name)}"`);
  lines.push(`tagline: "${esc(data.tagline)}"`);
  lines.push(`description: |`);
  data.description.split("\n").forEach((l) => lines.push(`  ${l}`));
  lines.push(`author: ${data.author}`);
  lines.push("categories:");
  data.categories.forEach((c) => lines.push(`  - ${c}`));
  if (data.tags.length > 0) {
    lines.push("tags:");
    data.tags.forEach((t) => lines.push(`  - ${t}`));
  }
  if (data.compatibleThemes.length > 0) {
    lines.push("compatible_themes:");
    data.compatibleThemes.forEach((t) => lines.push(`  - ${t}`));
  }
  if (data.screenshots.length > 0) {
    lines.push("screenshots:");
    data.screenshots.forEach((s) => lines.push(`  - ${s}`));
  }
  const selected = data.plugins.filter((p) => p.autoDetected);
  if (selected.length > 0) {
    lines.push("plugins:");
    selected.forEach((p) => {
      lines.push(`  - id: ${p.id}`);
      lines.push(`    name: ${p.name}`);
      lines.push(`    version: ${p.version}`);
    });
  }
  lines.push("environment:");
  lines.push(`  obsidian_version: "${data.obsidianVersion}"`);
  lines.push(`  theme: ${data.theme}`);
  lines.push(`  os: ${data.os}`);
  lines.push("files:");
  data.files.forEach((f) => {
    lines.push(`  - path: ${f.path}`);
    lines.push(`    type: ${f.type}`);
    lines.push(`    size: ${f.size}`);
  });
  return lines.join("\n") + "\n";
}
function esc(s) {
  return s.replace(/"/g, '\\"');
}

// src/readme.ts
function generateReadme(data) {
  var _a;
  const lines = [];
  lines.push(`# ${data.name}`);
  lines.push("");
  lines.push(data.tagline);
  lines.push("");
  lines.push("## Description");
  lines.push("");
  lines.push(data.description);
  lines.push("");
  const selected = data.plugins.filter((p) => p.autoDetected);
  if (selected.length > 0) {
    lines.push("## Required Plugins");
    lines.push("");
    lines.push("| Plugin | Version | Link |");
    lines.push("|--------|---------|------|");
    selected.forEach((p) => {
      lines.push(
        `| ${p.name} | ${p.version} | [GitHub](https://github.com/search?q=${encodeURIComponent(p.name + " obsidian")}) |`
      );
    });
    lines.push("");
  }
  lines.push("## Installation");
  lines.push("");
  if (data.type === "snippet") {
    lines.push(
      `1. Download \`${((_a = data.files[0]) == null ? void 0 : _a.path) || "snippet.css"}\` from this repo`
    );
    lines.push(
      "2. Place it in your vault's `.obsidian/snippets/` folder"
    );
    lines.push("3. Enable it in Settings > Appearance > CSS Snippets");
  } else {
    lines.push("1. Download the `.md` file(s) from this repo");
    lines.push("2. Place them in your vault");
    if (selected.length > 0) {
      lines.push("3. Install the required plugins listed above");
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("*Published via [Vault Hub](https://vaulthub.dev)*");
  lines.push("");
  return lines.join("\n");
}

// src/modals/PublishModal.ts
var CATEGORIES = {
  snippet: [
    "ui-tweak",
    "theme-override",
    "layout",
    "typography",
    "color-scheme",
    "editor",
    "sidebar",
    "publishing"
  ],
  note: [
    "dashboard",
    "tracker",
    "query",
    "daily-note",
    "project-template",
    "kanban",
    "database",
    "automation"
  ],
  bundle: [
    "dashboard",
    "tracker",
    "query",
    "project-template",
    "automation"
  ]
};
var PublishModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.step = 1;
    // Step 1
    this.resourceType = "snippet";
    this.selectedFiles = [];
    // Step 2
    this.allPlugins = [];
    this.checkedPlugins = /* @__PURE__ */ new Set();
    // Step 3
    this.name = "";
    this.tagline = "";
    this.description = "";
    this.categories = [];
    this.tags = "";
    this.compatibleThemes = [];
    // Step 4
    this.readmeContent = "";
    this.plugin = plugin;
  }
  onOpen() {
    this.renderStep();
  }
  onClose() {
    this.contentEl.empty();
  }
  renderStep() {
    this.contentEl.empty();
    this.contentEl.addClass("vault-hub-modal");
    const header = this.contentEl.createDiv("vault-hub-header");
    header.createEl("h2", { text: `Publish Resource \u2014 Step ${this.step} of 5` });
    const progress = header.createDiv("vault-hub-progress");
    for (let i = 1; i <= 5; i++) {
      const dot = progress.createSpan("vault-hub-dot");
      if (i === this.step)
        dot.addClass("active");
      else if (i < this.step)
        dot.addClass("done");
    }
    switch (this.step) {
      case 1:
        this.renderStep1();
        break;
      case 2:
        this.renderStep2();
        break;
      case 3:
        this.renderStep3();
        break;
      case 4:
        this.renderStep4();
        break;
      case 5:
        this.renderStep5();
        break;
    }
  }
  renderStep1() {
    const c = this.contentEl;
    new import_obsidian2.Setting(c).setName("Resource Type").addDropdown((dd) => {
      dd.addOption("snippet", "CSS Snippet");
      dd.addOption("note", "Note / Template");
      dd.addOption("bundle", "Bundle (multiple files)");
      dd.setValue(this.resourceType);
      dd.onChange((v) => {
        this.resourceType = v;
        this.selectedFiles = [];
        this.renderStep();
      });
    });
    const ext = this.resourceType === "snippet" ? ".css" : ".md";
    const files = this.app.vault.getFiles().filter((f) => f.extension === ext.slice(1)).sort((a, b) => a.path.localeCompare(b.path));
    const fileSection = c.createDiv();
    fileSection.createEl("h4", { text: `Select file${this.resourceType === "bundle" ? "s" : ""}` });
    const list = fileSection.createDiv("vault-hub-file-list");
    files.forEach((f) => {
      const row = list.createDiv("vault-hub-file-row");
      const cb = row.createEl("input", { type: this.resourceType === "bundle" ? "checkbox" : "radio" });
      cb.name = "vault-hub-file";
      cb.checked = this.selectedFiles.includes(f);
      cb.addEventListener("change", () => {
        if (this.resourceType === "bundle") {
          if (cb.checked)
            this.selectedFiles.push(f);
          else
            this.selectedFiles = this.selectedFiles.filter((x) => x !== f);
        } else {
          this.selectedFiles = cb.checked ? [f] : [];
        }
      });
      row.createSpan({ text: f.path });
    });
    this.addNav(c, null, () => {
      if (this.selectedFiles.length === 0) {
        new import_obsidian2.Notice("Select at least one file");
        return false;
      }
      return true;
    });
  }
  async renderStep2() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Select Required Plugins" });
    c.createEl("p", {
      text: "Auto-detected plugins are pre-checked. Review and adjust.",
      cls: "vault-hub-hint"
    });
    const loading = c.createDiv({ text: "Scanning..." });
    const content = await this.app.vault.read(this.selectedFiles[0]);
    const fileType = this.resourceType === "snippet" ? "css" : "md";
    this.allPlugins = await detectPlugins(content, fileType, this.app.vault);
    loading.remove();
    this.allPlugins.forEach((p) => {
      if (p.autoDetected)
        this.checkedPlugins.add(p.id);
    });
    const list = c.createDiv("vault-hub-plugin-list");
    this.allPlugins.forEach((p) => {
      const row = list.createDiv("vault-hub-plugin-row");
      const cb = row.createEl("input", { type: "checkbox" });
      cb.checked = this.checkedPlugins.has(p.id);
      cb.addEventListener("change", () => {
        if (cb.checked)
          this.checkedPlugins.add(p.id);
        else
          this.checkedPlugins.delete(p.id);
      });
      const info = row.createDiv("vault-hub-plugin-info");
      info.createSpan({ text: p.name, cls: "vault-hub-plugin-name" });
      info.createSpan({ text: ` v${p.version}`, cls: "vault-hub-plugin-version" });
      if (p.autoDetected) {
        info.createSpan({ text: " (auto-detected)", cls: "vault-hub-auto-badge" });
      }
    });
    if (this.allPlugins.length === 0) {
      c.createEl("p", { text: "No community plugins installed.", cls: "vault-hub-hint" });
    }
    this.addNav(c, null, null);
  }
  renderStep3() {
    const c = this.contentEl;
    new import_obsidian2.Setting(c).setName("Name").addText((t) => {
      t.setPlaceholder("My Resource").setValue(this.name);
      t.onChange((v) => this.name = v);
      t.inputEl.style.width = "100%";
    });
    new import_obsidian2.Setting(c).setName("Tagline").setDesc("One-line summary").addText((t) => {
      t.setPlaceholder("A brief description").setValue(this.tagline);
      t.onChange((v) => this.tagline = v);
      t.inputEl.style.width = "100%";
    });
    new import_obsidian2.Setting(c).setName("Description").addTextArea((t) => {
      t.setPlaceholder("Detailed description...").setValue(this.description);
      t.onChange((v) => this.description = v);
      t.inputEl.style.width = "100%";
      t.inputEl.style.minHeight = "80px";
    });
    const cats = CATEGORIES[this.resourceType] || [];
    new import_obsidian2.Setting(c).setName("Category").addDropdown((dd) => {
      dd.addOption("", "Select...");
      cats.forEach((cat) => dd.addOption(cat, cat));
      dd.setValue(this.categories[0] || "");
      dd.onChange((v) => this.categories = v ? [v] : []);
    });
    new import_obsidian2.Setting(c).setName("Tags").setDesc("Comma-separated").addText((t) => {
      t.setPlaceholder("glass, blur, dark").setValue(this.tags);
      t.onChange((v) => this.tags = v);
    });
    if (this.resourceType === "snippet") {
      new import_obsidian2.Setting(c).setName("Compatible Themes").addDropdown((dd) => {
        dd.addOption("any", "Any theme");
        ["minimal", "velocity", "obsidian-default", "catppuccin"].forEach(
          (t) => dd.addOption(t, t)
        );
        dd.setValue(this.compatibleThemes[0] || "any");
        dd.onChange((v) => this.compatibleThemes = [v]);
      });
    }
    this.addNav(c, null, () => {
      if (!this.name.trim()) {
        new import_obsidian2.Notice("Name is required");
        return false;
      }
      const selected = this.allPlugins.filter((p) => this.checkedPlugins.has(p.id)).map((p) => ({ ...p, autoDetected: true }));
      const readmeData = {
        name: this.name,
        tagline: this.tagline,
        description: this.description,
        type: this.resourceType,
        plugins: selected,
        files: this.selectedFiles.map((f) => ({ path: f.name }))
      };
      this.readmeContent = generateReadme(readmeData);
      return true;
    });
  }
  renderStep4() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Edit README" });
    c.createEl("p", {
      text: "Auto-generated from your details. Edit freely.",
      cls: "vault-hub-hint"
    });
    const textarea = c.createEl("textarea", { cls: "vault-hub-readme-editor" });
    textarea.value = this.readmeContent;
    textarea.addEventListener("input", () => {
      this.readmeContent = textarea.value;
    });
    this.addNav(c, null, null);
  }
  renderStep5() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Review & Publish" });
    const summary = c.createDiv("vault-hub-summary");
    summary.createEl("p", { text: `Type: ${this.resourceType}` });
    summary.createEl("p", { text: `Name: ${this.name}` });
    summary.createEl("p", { text: `Files: ${this.selectedFiles.map((f) => f.name).join(", ")}` });
    const selPlugins = this.allPlugins.filter((p) => this.checkedPlugins.has(p.id));
    summary.createEl("p", {
      text: `Plugins: ${selPlugins.length > 0 ? selPlugins.map((p) => p.name).join(", ") : "None"}`
    });
    summary.createEl("p", { text: `Categories: ${this.categories.join(", ") || "None"}` });
    const btnContainer = c.createDiv("vault-hub-nav");
    const backBtn = btnContainer.createEl("button", { text: "Back" });
    backBtn.addEventListener("click", () => {
      this.step--;
      this.renderStep();
    });
    const publishBtn = btnContainer.createEl("button", {
      text: "Publish",
      cls: "mod-cta"
    });
    publishBtn.addEventListener("click", () => this.doPublish());
  }
  async doPublish() {
    var _a;
    const token = this.plugin.settings.githubToken;
    if (!token) {
      new import_obsidian2.Notice("Set your GitHub token in Vault Hub settings first");
      return;
    }
    const c = this.contentEl;
    c.empty();
    c.createEl("h3", { text: "Publishing..." });
    const status = c.createEl("p", { text: "Creating repository..." });
    try {
      const gh = new GitHubAPI(token);
      const user = await gh.getUser();
      const slug = this.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      const repoName = `obsidian-${this.resourceType}-${slug}`;
      status.setText("Creating repository...");
      const repo = await gh.createRepo(repoName, this.tagline || this.name);
      const [owner, rName] = repo.full_name.split("/");
      const topicMap = {
        snippet: "obsidian-css-snippet",
        note: "obsidian-note-template",
        bundle: "obsidian-note-template"
      };
      status.setText("Adding topic tag...");
      await gh.addTopics(owner, rName, [topicMap[this.resourceType]]);
      for (const file of this.selectedFiles) {
        status.setText(`Uploading ${file.name}...`);
        const content = await this.app.vault.read(file);
        await gh.createFile(owner, rName, file.name, content, `Add ${file.name}`);
      }
      status.setText("Generating hub.yml...");
      const selectedPlugins = this.allPlugins.filter((p) => this.checkedPlugins.has(p.id)).map((p) => ({ ...p, autoDetected: true }));
      const obsVer = this.app.appVersion || "unknown";
      const themeName = ((_a = this.app.vault.config) == null ? void 0 : _a.cssTheme) || "default";
      const hubData = {
        type: this.resourceType,
        name: this.name,
        tagline: this.tagline,
        description: this.description,
        author: user.login,
        categories: this.categories,
        tags: this.tags.split(",").map((t) => t.trim()).filter(Boolean),
        compatibleThemes: this.compatibleThemes,
        screenshots: [],
        plugins: selectedPlugins,
        obsidianVersion: obsVer,
        theme: themeName,
        os: navigator.platform,
        files: this.selectedFiles.map((f) => ({
          path: f.name,
          type: f.extension,
          size: f.stat.size
        }))
      };
      const hubYml = generateHubYml(hubData);
      await gh.createFile(owner, rName, "hub.yml", hubYml, "Add hub.yml");
      status.setText("Uploading README...");
      await gh.createFile(owner, rName, "README.md", this.readmeContent, "Add README");
      this.plugin.settings.publishedResources.push({
        repoFullName: repo.full_name,
        localFilePath: this.selectedFiles[0].path,
        type: this.resourceType,
        lastPublishedAt: (/* @__PURE__ */ new Date()).toISOString()
      });
      await this.plugin.saveSettings();
      c.empty();
      c.createEl("h3", { text: "Published!" });
      c.createEl("p", { text: `Repository: ${repo.full_name}` });
      const link = c.createEl("a", {
        text: repo.html_url,
        href: repo.html_url
      });
      link.setAttr("target", "_blank");
      c.createEl("p", {
        text: "It will appear on Vault Hub within 6 hours.",
        cls: "vault-hub-hint"
      });
      const closeBtn = c.createEl("button", { text: "Close", cls: "mod-cta" });
      closeBtn.addEventListener("click", () => this.close());
      new import_obsidian2.Notice(`Published to ${repo.full_name}!`);
    } catch (e) {
      c.empty();
      c.createEl("h3", { text: "Error" });
      c.createEl("p", { text: String(e) });
      const retryBtn = c.createEl("button", { text: "Back to Review" });
      retryBtn.addEventListener("click", () => {
        this.step = 5;
        this.renderStep();
      });
    }
  }
  addNav(container, backCheck, nextCheck) {
    const nav = container.createDiv("vault-hub-nav");
    if (this.step > 1) {
      const back = nav.createEl("button", { text: "Back" });
      back.addEventListener("click", () => {
        if (backCheck && !backCheck())
          return;
        this.step--;
        this.renderStep();
      });
    }
    if (this.step < 5) {
      const next = nav.createEl("button", { text: "Next", cls: "mod-cta" });
      next.addEventListener("click", () => {
        if (nextCheck && !nextCheck())
          return;
        this.step++;
        this.renderStep();
      });
    }
  }
};

// src/modals/UpdateModal.ts
var import_obsidian3 = require("obsidian");
var UpdateModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.selected = null;
    this.plugin = plugin;
  }
  onOpen() {
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.createEl("h2", { text: "Update Published Resource" });
    const resources = this.plugin.settings.publishedResources;
    if (resources.length === 0) {
      c.createEl("p", { text: "No published resources yet. Use Publish first." });
      return;
    }
    new import_obsidian3.Setting(c).setName("Select Resource").addDropdown((dd) => {
      dd.addOption("", "Choose...");
      resources.forEach((r, i) => {
        dd.addOption(String(i), `${r.repoFullName} (${r.type})`);
      });
      dd.onChange((v) => {
        this.selected = v ? resources[parseInt(v)] : null;
      });
    });
    const updateBtn = c.createEl("button", { text: "Push Update", cls: "mod-cta" });
    updateBtn.addEventListener("click", () => this.doUpdate());
  }
  async doUpdate() {
    if (!this.selected) {
      new import_obsidian3.Notice("Select a resource first");
      return;
    }
    const token = this.plugin.settings.githubToken;
    if (!token) {
      new import_obsidian3.Notice("Set your GitHub token in settings first");
      return;
    }
    const c = this.contentEl;
    c.empty();
    c.createEl("h3", { text: "Updating..." });
    try {
      const gh = new GitHubAPI(token);
      const [owner, repo] = this.selected.repoFullName.split("/");
      const file = this.app.vault.getAbstractFileByPath(this.selected.localFilePath);
      if (!file) {
        new import_obsidian3.Notice(`File not found: ${this.selected.localFilePath}`);
        return;
      }
      const content = await this.app.vault.read(file);
      const existing = await gh.getFileContent(owner, repo, file.name);
      if (existing) {
        await gh.updateFile(
          owner,
          repo,
          file.name,
          content,
          `Update ${file.name}`,
          existing.sha
        );
      } else {
        await gh.createFile(owner, repo, file.name, content, `Add ${file.name}`);
      }
      this.selected.lastPublishedAt = (/* @__PURE__ */ new Date()).toISOString();
      await this.plugin.saveSettings();
      c.empty();
      c.createEl("h3", { text: "Updated!" });
      c.createEl("p", { text: `Pushed to ${this.selected.repoFullName}` });
      const closeBtn = c.createEl("button", { text: "Close", cls: "mod-cta" });
      closeBtn.addEventListener("click", () => this.close());
      new import_obsidian3.Notice("Resource updated!");
    } catch (e) {
      c.empty();
      c.createEl("h3", { text: "Error" });
      c.createEl("p", { text: String(e) });
    }
  }
};

// src/views/BrowseView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_BROWSE = "vault-hub-browse";
var SUPABASE_URL = "https://oxvxiqiushhpwzqtpzdg.supabase.co";
var SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dnhpcWl1c2hocHd6cXRwemRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0MTI4NjAsImV4cCI6MjA5MDk4ODg2MH0.jOJloJvJmV2Q-xuY1wBbUjg0s7DnRGt6htycj4HBtEA";
var BrowseView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.searchQuery = "";
    this.resources = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_BROWSE;
  }
  getDisplayText() {
    return "Vault Hub";
  }
  getIcon() {
    return "globe";
  }
  async onOpen() {
    this.render();
    await this.loadResources();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.addClass("vault-hub-browse");
    const header = c.createDiv("vault-hub-browse-header");
    header.createEl("h3", { text: "Vault Hub" });
    const searchRow = header.createDiv("vault-hub-search-row");
    const input = searchRow.createEl("input", {
      type: "text",
      placeholder: "Search resources..."
    });
    input.value = this.searchQuery;
    input.addEventListener("input", () => {
      this.searchQuery = input.value;
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        this.loadResources();
    });
    const searchBtn = searchRow.createEl("button", { text: "Search" });
    searchBtn.addEventListener("click", () => this.loadResources());
    c.createDiv("vault-hub-results");
  }
  async loadResources() {
    const resultsEl = this.contentEl.querySelector(".vault-hub-results");
    if (!resultsEl)
      return;
    resultsEl.empty();
    resultsEl.createEl("p", { text: "Loading...", cls: "vault-hub-hint" });
    try {
      let url = `${SUPABASE_URL}/rest/v1/resources?select=id,type,title,owner,repo_name,full_name,tagline,stars,vote_count&is_active=eq.true&order=trending_score.desc&limit=30`;
      if (this.searchQuery.trim()) {
        url += `&or=(title.ilike.*${encodeURIComponent(this.searchQuery)}*,description.ilike.*${encodeURIComponent(this.searchQuery)}*)`;
      }
      const res = await fetch(url, {
        headers: {
          apikey: SUPABASE_KEY,
          Authorization: `Bearer ${SUPABASE_KEY}`
        }
      });
      this.resources = await res.json();
      this.renderResults(resultsEl);
    } catch (e) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: `Error: ${e}` });
    }
  }
  renderResults(container) {
    container.empty();
    if (this.resources.length === 0) {
      container.createEl("p", {
        text: "No resources found.",
        cls: "vault-hub-hint"
      });
      return;
    }
    this.resources.forEach((r) => {
      const card = container.createDiv("vault-hub-result-card");
      const typeColors = {
        vault: "#7f6df2",
        snippet: "#22d3ee",
        note: "#fb923c"
      };
      const badge = card.createSpan("vault-hub-type-badge");
      badge.setText(r.type);
      badge.style.backgroundColor = typeColors[r.type] || "#666";
      const title = card.createEl("h4");
      title.setText(r.title);
      if (r.tagline) {
        card.createEl("p", { text: r.tagline, cls: "vault-hub-hint" });
      }
      const meta = card.createDiv("vault-hub-result-meta");
      meta.createSpan({ text: `${r.stars} stars` });
      meta.createSpan({ text: `${r.vote_count} votes` });
      meta.createSpan({ text: r.owner });
      const actions = card.createDiv("vault-hub-result-actions");
      const installBtn = actions.createEl("button", { text: "Install" });
      installBtn.addEventListener("click", () => this.installResource(r));
      const ghBtn = actions.createEl("button", { text: "GitHub" });
      ghBtn.addEventListener("click", () => {
        window.open(`https://github.com/${r.full_name}`, "_blank");
      });
    });
  }
  async installResource(r) {
    try {
      const res = await fetch(
        `https://api.github.com/repos/${r.full_name}/contents`,
        { headers: { Accept: "application/vnd.github.v3+json" } }
      );
      const files = await res.json();
      if (r.type === "snippet") {
        const cssFile = files.find(
          (f) => f.name.endsWith(".css")
        );
        if (cssFile) {
          const raw = await fetch(cssFile.download_url);
          const content = await raw.text();
          const snippetPath = `${this.app.vault.configDir}/snippets/${cssFile.name}`;
          await this.app.vault.adapter.write(snippetPath, content);
          new import_obsidian4.Notice(`Installed snippet: ${cssFile.name}`);
        }
      } else {
        const mdFiles = files.filter(
          (f) => f.name.endsWith(".md") && f.name !== "README.md"
        );
        for (const f of mdFiles) {
          const raw = await fetch(f.download_url);
          const content = await raw.text();
          await this.app.vault.create(f.name, content);
          new import_obsidian4.Notice(`Installed: ${f.name}`);
        }
      }
    } catch (e) {
      new import_obsidian4.Notice(`Install failed: ${e}`);
    }
  }
};

// src/main.ts
var VaultHubPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_BROWSE, (leaf) => new BrowseView(leaf, this));
    this.addCommand({
      id: "publish-resource",
      name: "Publish Resource",
      callback: () => new PublishModal(this.app, this).open()
    });
    this.addCommand({
      id: "update-resource",
      name: "Update Resource",
      callback: () => new UpdateModal(this.app, this).open()
    });
    this.addCommand({
      id: "browse-resources",
      name: "Browse Resources",
      callback: () => this.activateBrowseView()
    });
    this.addSettingTab(new VaultHubSettingTab(this.app, this));
    this.addRibbonIcon("globe", "Vault Hub", () => {
      this.activateBrowseView();
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateBrowseView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_BROWSE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_BROWSE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
